check50:
    files: &check50_files
        - !exclude "*"
        - !include "number"
        - !include "number.cpp"
        - !include "util.cpp"
        - !include "util.h"
        - !include "Makefile"

submit50:
    files: *check50_files