check50:
    files: &check50_files
        - !exclude "*"
        - !include "math"
        - !include "main.cpp"
        - !include "math.cpp"
        - !include "math.h"
        - !include "Makefile"

submit50:
    files: *check50_files