check50:
    files: &check50_files
        - !exclude "*"
        - !include "MathSet.java"
        - !include "MathSet.class"
        - !include "Tester.java"
        - !include "Tester.class"
        - !include "mathsetdata.dat"

submit50:
    files: *check50_files