check50:
    files: &check50_files
        - !exclude "*"
        - !include "Acronyms.java"
        - !include "Acronyms.class"
        - !include "Checker.java"
        - !include "Checker.class"
        - !include "acronyms.dat"

submit50:
    files: *check50_files