check50:
    files: &check50_files
        - !exclude "*"
        - !include "UniquesDupes.java"
        - !include "UniquesDupes.class"
        - !include "DupRunner.java"
        - !include "DupRunner.class"
        - !include "Tester.java"
        - !include "Tester.class"

submit50:
    files: *check50_files
