check50:
    files: &check50_files
        - !exclude "*"
        - !include "SpanToEng.java"
        - !include "SpanToEng.class"
        - !include "Checker.java"
        - !include "Checker.class"
        - !include "spantoeng.dat"

submit50:
    files: *check50_files