check50:
    files: &check50_files
        - !exclude "*"
        - !include "Gem.java"
        - !include "Gem.class"
        - !include "GemList.java"
        - !include "GemList.class"
        - !include "GemList$Node.class"
        - !include "GemGame.java"
        - !include "GemGame.class"
        - !include "StdDraw.java"
        - !include "StdDraw.class"
        - !include "GemType.class"
        - !include "gem_blue.png"
        - !include "gem_green.png"
        - !include "gem_orange.png"

submit50:
    files: *check50_files