check50:
    files: &check50_files
        - !exclude "*"
        - !include "magic"
        - !include "magic.cpp"
        - !include "util.cpp"
        - !include "util.h"
        - !include "Makefile"
        - !include "magic_data.txt"

submit50:
    files: *check50_files