check50:
    files: &check50_files
        - !exclude "*"
        - !include "BST.java"
        - !include "BST.class"
        - !include "BST$Node.class"
        - !include "BST$TreeNode.class"

submit50:
    files: *check50_files