check50:
    files: &check50_files
        - !exclude "*"
        - !include "*.java"
        - !include "*.class"
        - !require "IteratorRemover.java"
        - !require "IteratorRemover.class"

submit50:
    files: *check50_files