check50:
    files: &check50_files
        - !exclude "*"
        - !include "BSTBasic.java"
        - !include "BSTBasic.class"
        - !include "BSTBasic$Node.class"

submit50:
    files: *check50_files