check50:
    files: &check50_files
        - !exclude "*"
        - !include "MyLinkedList.java"
        - !include "MyLinkedList.class"
        - !include "MyLinkedList$ListNode.class"

submit50:
    files: *check50_files