check50:
    files: &check50_files
        - !exclude "*"
        - !include "BSTComplete.java"
        - !include "BSTComplete.class"
        - !include "BSTComplete$Node.class"

submit50:
    files: *check50_files